dropPlayerTable NA DROP TABLE IF EXISTS players;
createPlayerTable NA CREATE TABLE IF NOT EXISTS players(PlayerName VARCHAR(24) PRIMARY KEY NOT NULL, PlayerPasswordHash VARCHAR(32) NOT NULL, PlayerIP VARCHAR(32) NOT NULL, PlayerLevel INTEGER NOT NULL, PlayerScore INTEGER NOT NULL, PlayerMoney INTEGER NOT NULL);
createPlayer sssddd INSERT INTO players (PlayerName,PlayerPasswordHash, PlayerIP, PlayerLevel, PlayerScore, PlayerMoney) VALUES ('%s','%s','%s',%d,%d,%d);
getPlayerProperty ss SELECT %s FROM players WHERE PlayerName='%s';
updatePlayerPropertyString sss UPDATE players SET %s='%s' WHERE PlayerName='%s';
createPropertiesTable NA CREATE TABLE IF NOT EXISTS properties(ID INTEGER PRIMARY KEY NOT NULL, PropName VARCHAR(32) NOT NULL, PropCost INTEGER NOT NULL, PropEarnings INTEGER NOT NULL, PropOwner VARCHAR(32) NOT NULL, PropPurchaseTime INTEGER, PropLocX FLOAT NOT NULL, PropLocY FLOAT NOT NULL, PropLocZ FLOAT NOT NULL);
dropPropertiesTable NA DROP TABLE IF EXISTS properties;
findAllProperties NA SELECT * FROM properties;
updatePropertyId dd UPDATE properties SET ID=%d WHERE ID=%d;
findPropertyByPickupID d SELECT * FROM properties WHERE ID=%d;
createProperty dsddfff INSERT INTO properties (ID,PropName, PropCost, PropEarnings, PropOwner, PropLocX, PropLocY, PropLocZ) VALUES (%d,'%s',%d,%d,'',%f,%f,%f);
updateProperty sdd UPDATE properties SET PropOwner='%s',PropPurchaseTime=%d WHERE ID=%d;
createRaceTable NA CREATE TABLE IF NOT EXISTS race(ID INTEGER PRIMARY KEY NOT NULL,RaceName VARCHAR(32) NOT NULL,CreatorName VARCHAR(32), RecordTime INTEGER, RecordHolder VARCHAR(32), VehicleModel INTEGER, NumCheck INTEGER, Distance FLOAT, Active INTEGER);
dropRaceTable NA DROP TABLE IF EXISTS race;
createNewRace ss INSERT INTO race(RaceName,CreatorName,RecordTime,RecordHolder,VehicleModel,NumCheck,Distance,Active) VALUES('%s','%s',0,'',0,0,0,0);
createRaceCheckpointsTable NA CREATE TABLE IF NOT EXISTS race_cp(ID INTEGER PRIMARY KEY NOT NULL, RaceID INTEGER NOT NULL, X FLOAT, Y FLOAT, Z FLOAT, Num INTEGER);
dropRaceCheckpointsTable NA DROP TABLE IF EXISTS race_cp;
findRaceByName s SELECT * from race WHERE RaceName = '%s';
findAllRaces NA SELECT * FROM race;
createRaceCheckpoint dfffd INSERT INTO race_cp(RaceID,X,Y,Z,Num) VALUES(%d,%f,%f,%f,%d);
updateRaceStr ssd UPDATE race SET %s = '%s' WHERE ID = %d;
updateRaceInt sdd UPDATE race SET %s = %d WHERE ID = %d;
updateRaceFloat sfd UPDATE race SET %s = %f WHERE ID = %d;
findRandomRace NA SELECT * FROM RACE WHERE Active = 1 ORDER BY RANDOM() LIMIT 1;
findRaceByID d SELECT * FROM RACE WHERE ID = %d;
findCheckpointsByRaceID d SELECT * FROM race_cp WHERE RaceID = %d ORDER BY Num ASC;
createConfigurationTable NA CREATE TABLE IF NOT EXISTS configuration(ID INTEGER PRIMARY KEY NOT NULL, CfgKey VARCHAR(32), CfgValue VARCHAR(32));
findConfigurationByKey s SELECT * FROM configuration WHERE CfgKey='%s';
findAllConfigurations NA SELECT * FROM configuration;
createNewConfiguration ss INSERT INTO configuration(CfgKey, CfgValue) VALUES('%s','%s');
updateConfigurationValue ss UPDATE configuration SET CfgValue='%s' WHERE CfgKey='%s';
